# Generated by Django 3.2.8 on 2021-11-09 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('alert_date', models.DateField()),
                ('alert_time', models.TimeField()),
                ('total_victims', models.IntegerField(default=0)),
                ('accident_date', models.DateField()),
                ('accident_time', models.TimeField()),
                ('resources', models.CharField(blank=True, default='', max_length=2048)),
                ('place', models.CharField(blank=True, default='', max_length=2048)),
                ('circumstances', models.CharField(blank=True, default='', max_length=2048)),
            ],
        ),
    ]
